Adauga tutorial Docker
alexcoman/teaching.alexcoman.com pull request #22
Opened 2017-04-04 20:29 UTC by stefan-caraiman

WiP

2017-04-05 16:42 UTC, alexcoman requested changes
Câteva lucruri de care te rog să ții cont:
- trebuie să folosești diacritice
- evită pe cât posibil să folosești termeni englezești dacă există o alternativă potrivită în limba română
- o să fie nevoie de mai multe detalii pentru fiecare subcapitol

2017-04-05 16:42 UTC, alexcoman commented on _posts/tutorial/2017-04-04-docker-notiuni-introductive.markdown
> +
Renunță la linia goală.

2017-04-05 16:42 UTC, alexcoman commented on _posts/tutorial/2017-04-04-docker-notiuni-introductive.markdown
> +```
bash

2017-04-05 16:42 UTC, alexcoman commented on _posts/tutorial/2017-04-04-docker-notiuni-introductive.markdown
> +```
Ditto.

2017-04-11 20:07 UTC, micumatei commented
Ca sa adaug putin hate as zice ca trebuie sa le explici cum merge putin (docker image, cum sa isi faca o imagine ce inseamna fiecare parametru din comanda si ce face )
`sudo docker run -p 80:80 -v /home/stefanc/proiect/src/:/var/www/html/ proiect-php`
Daca stii ce e docker asta face sens. SI ca sa fie si mai mult hate : 
- `-p 80:80` nu e okay, foloseste `1024+` si daca faci asta nu o sa mai ai nevoie de sudo 
-  `-v /home/stefanc/proiect/src/:/var/www/html/ ` aici folosesti un path din env-ul tau ( cred ca merge si cu ceva relativ )
- `proiect-php` exista imaginea asta ?

Apoi trebuie sa adaugi info despre cum sa vada ce containere ruleaza cum sa le stearga ( cum sa vada care is oprite sa nu aiba containere oprite dar nu sterse )

2017-04-12 07:39 UTC, alexcoman commented
Salut @micumatei și @stefan-caraiman,

Pentru început cred că ar fi foarte util de stabilit structura articolului și nivelul de complexitate.
Consider că ar fi important ca acest articol să răspundă la următoarele întrebări:

1. Ce este un container ?
2. Care sunt avantajele folosirii unui container (eventual comparație cu o mașină virtuală) ?
3. Unde este recomandat să folosim un container ?
4. Cum pot să folosesc această tehnologie ?
5. Ce este o imagine și ce proprietăți are aceasta ?
6. Cum interacționez cu containerele ?

După prezentarea generală se pot adăuga ulterior articole mult mai specifice pentru diverse scenarii.

Mulțumesc de ajutor!

/Alex

2017-05-23 09:20 UTC, closed without merging