Add 'OpenStack deployment with DevStack' tutorial
alexcoman/teaching.alexcoman.com pull request #34
Opened 2017-05-15 19:29 UTC by alexcoman

2017-05-15 20:57 UTC, mateimicu requested changes

2017-05-15 20:57 UTC, micumatei commented on _posts/tutorial/openstack/2017-05-15-instalare-openstack-folosind-devstack.markdown
> +**Avertisment**: acest lucru va scadea securitatea sistemului de operare.
sc**ă**dea

2017-05-15 20:57 UTC, micumatei commented on _posts/tutorial/openstack/2017-05-15-instalare-openstack-folosind-devstack.markdown
> +Pasul următor este să configurăm static interfața pe care o să expunem interfața web.
Aici vorbesti de `interfața` si cand te referi la NIC si cand te referi la horizon si e putin confusing.
Maybe:
```
Pasul .....**prin** care o să expunem **Horizon**-> de la horizon link cartre ce e 
```

2017-05-16 08:02 UTC, alexcoman commented on _posts/tutorial/openstack/2017-05-15-instalare-openstack-folosind-devstack.markdown
> +**Avertisment**: acest lucru va scadea securitatea sistemului de operare.
Done.

2017-05-16 08:03 UTC, alexcoman commented on _posts/tutorial/openstack/2017-05-15-instalare-openstack-folosind-devstack.markdown
> +Pasul următor este să configurăm static interfața pe care o să expunem interfața web.
Done.

2017-05-16 08:50 UTC, merged