Add 'OpenStack deployment with Packstack' tutorial
alexcoman/teaching.alexcoman.com pull request #35
Opened 2017-05-15 20:50 UTC by micumatei

2017-05-15 20:57 UTC, alexcoman requested changes

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> +---
Poți schimba în numele fișierului  `folosind` în loc de `cu`.

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> +categories: [tutorial, virtualbox, openstack]
Ca și categorie cred că e mai okay [tutorial, openstack].

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> +Acest tutorial vine în ajutorul studenților ce doresc să își pregătească o mașină virtuală care va contine un mediu de executie OpensStack RDO([RedHat Deployment of OpenStack](RDO))
execuție

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> + - ISO-ul pe care il folosiți trebuie sa contină GUI
GUI (interfață grafică)

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> +Deoarece rețelele de tip **NAT** din [VirtualBox] sunt izolate(nu pot fi accesate din mașina gazdă) trebuie să facem port forwarding a portului 80 (cel pe care este expos [Horizon], interfața web pri
expus

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> +Pentru asta din VirtualBox accesăm **Settings** > **Network** > **Advance** > **Port Forwarding** și adaugam urmatoarele regului:
Pentru acest lucru accesăm **Port Forwarding** din meniul ...

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> +Pentru a configura detaliile instalări [Packstack] foloseste un fișier care poate fi generat de la linia de comandă în următorul mod:
folosind următoarea comandă

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> +Veți avem un fișier care arată asemanator cu urmatoarea imagine:
Rezultatul comenzii de mai sus este un fișier asemănător cu. ..

2017-05-15 20:57 UTC, alexcoman commented on _posts/tutorial/virtualbox/2017-05-14-instalare-openstack-cu-packstack.markdown
> +Dupa ce am configurat tot putem să pornim instalarea folosind comanda:
După personalizarea fișierului de configurare ...

2017-05-15 22:38 UTC, micumatei commented
Facut update la tutorial ! @alexcoman

2017-05-16 08:06 UTC, alexcoman approved these changes

2017-05-16 08:07 UTC, alexcoman commented
@micumatei mută te rog articolul în `_post/tutorial/openstack`.

2017-05-16 10:09 UTC, merged